import numpy as np
import pandas as pd

# Define the number of samples to generate
n_samples = 10

# Define the ranges of the input variables
temp_range = (0, 50)              # Temperature in degrees Celsius
sun_range = (0, 1000)             # Sunlight intensity in watts per square meter
hum_range = (0, 100)              # Humidity as a percentage
orient_range = (0, 360)           # Panel orientation in degrees
pos_range = (0, 90)               # Panel position in degrees from the horizontal plane

# Generate values for the input variables
temperature = np.random.uniform(low=temp_range[0], high=temp_range[1], size=n_samples)
sunlight_intensity = np.random.uniform(low=sun_range[0], high=sun_range[1], size=n_samples)
humidity = np.random.uniform(low=hum_range[0], high=hum_range[1], size=n_samples)
orient = np.random.uniform(low=orient_range[0], high=orient_range[1], size=n_samples)
pos = np.random.uniform(low=pos_range[0], high=pos_range[1], size=n_samples)

# Calculate the current generated by the solar panel using a linear combination of the input variables
current_generated = 0.5*temperature + 0.2*sunlight_intensity + 0.3*humidity + 0.001*orient + 0.002*pos

# Create a Pandas dataframe with the simulated data
data = pd.DataFrame({'Temperature': temperature,
                     'Sunlight_Intensity': sunlight_intensity,
                     'Humidity': humidity,
                     'Panel_Orientation': orient,
                     'Panel_Position': pos,
                     'Current_Generated': current_generated})

# Save the data to a CSV file
data.to_csv('data_simulated_10.csv', index=False)
